---
- name: Setup EC2 cluster inside the VPC
  hosts: localhost
  vars:
    ecs_cluster_name: 'DDACK_Cluster'
    ecs_ssh_key_name: 'DDACK_key'
    ecs_security_groups: 'DDACK_SG1'
    ecs_vpc_subnets: ["{{ subnet_result.subnet.id }}", "{{ subnet_result2.subnet.id }}"]
    ecs_asg_min_size: 2
    ecs_asg_max_size: 4
    ecs_asg_desired_capacity: 2
    ecs_ec2_tags:
         Name: "DDACK_web"
         role: "ecs-cluster"
    ecs_ec2_region: ap-northeast-2  
  roles:
    - role-create-ec2
    - ansible-role-ecs-cluster

  tasks:  
    - name: Create task definition for a service running in docker container(s)
      ecs_taskdefinition:
        family: DDACK_family
        containers:
          - name: DDACK_app
            cpu: 256
            memory: 500
            image: seokkyung/web-nginx
            # needs more params here, see docs
        region: "{{ ecs_ec2_region }}"
        state: present
      register: my_task_definition

    - name: Create service running on the ECS cluster
      ecs_service:
        name: DDACK_service
        cluster: "{{ ecs_cluster_name }}"
        task_definition: "{{ my_task_definition.taskdefinition.taskDefinitionArn }}"
        region: "{{ ecs_ec2_region }}"
        desired_count: 1
        state: present

